# Generated by Django 3.1.6 on 2021-06-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210627_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='ordered_date',
            new_name='date_ordered',
        ),
    ]
