# Generated by Django 3.1.6 on 2021-06-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210628_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='date_ordered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
