# Generated by Django 3.1.6 on 2021-06-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210630_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
